version: '3.8'

services:
  pocketbase:
    build: .
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data
      - ./pb_public:/pb_public
      - ./pb_hooks:/pb_hooks
      - ./pb_migrations:/pb_migrations
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - SERVICE_FQDN_POCKETBASE=/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pocketbase.rule=Host(`${SERVICE_FQDN}`) && PathPrefix(`/`)"
      - "traefik.http.services.pocketbase.loadbalancer.server.port=8090"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3